---
- name: GRUB | Look for /etc/default/grub
  ansible.builtin.stat:
    path: /etc/default/grub
  register: _grub_defaults

- name: GRUB | Apply settings
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^{{ item.key }}="
    line: '{{ item.key }}="{{ item.value }}"'
  loop: "{{ grub_settings | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: _grub_defaults.stat.exists
  notify: Regenerate GRUB

- name: GRUB | Remove obsolete settings
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^{{ item }}="
    state: absent
  loop: "{{ grub_settings_absent }}"
  when: _grub_defaults.stat.exists
  notify: Regenerate GRUB
