---
- name: Verify | Fedora 44, personal
  hosts: all
  tasks:
    - name: Verify | Installed
      ansible.builtin.include_tasks: ../shared/verify_installed.yml

    - name: Verify | Steam, ASUS (forced) and ClamAV features are on
      ansible.builtin.assert:
        that: alpi_feature.steam and alpi_feature.asus and alpi_feature.clamav
        quiet: true
